import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import PageTopNav from '../components/PageTopNav';
import { useAuth } from '../context/AuthContext';
import { fetchDashboardRecommendation } from '../services/dashboardAI';
import { buildDashboardAnalytics, getLocalRecommendation, getReadinessLabel, readTestHistory } from '../services/dashboardAnalytics';
import { getVerifiedTrainee } from '../services/traineeVerification';

function formatTime(seconds) {
  const minutes = Math.floor(Number(seconds || 0) / 60);
  const secs = Number(seconds || 0) % 60;
  return `${minutes}m ${secs.toString().padStart(2, '0')}s`;
}

function MetricCard({ label, value, detail, tone = 'neutral' }) {
  return (
    <article className={`analytics-metric ${tone}`}>
      <span>{label}</span>
      <strong>{value}</strong>
      <em>{detail}</em>
    </article>
  );
}

function ScoreTrendChart({ items, passMark }) {
  const points = items.length > 1
    ? items.map((item, index) => {
      const x = (index / (items.length - 1)) * 100;
      const y = 100 - ((item.score / item.total) * 100);
      return `${x},${y}`;
    }).join(' ')
    : '';

  return (
    <div className="chart-card">
      <div className="chart-head">
        <div>
          <h3>Score Trend</h3>
          <span>Last {items.length || 0} attempts</span>
        </div>
        <strong>{passMark}/20 target</strong>
      </div>

      {items.length ? (
        <>
          <svg className="trend-chart" viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Score trend chart">
            <line x1="0" x2="100" y1={100 - ((passMark / 20) * 100)} y2={100 - ((passMark / 20) * 100)} className="pass-line" />
            {items.length > 1 && <polyline points={points} className="score-line-chart" />}
            {items.map((item, index) => {
              const x = items.length > 1 ? (index / (items.length - 1)) * 100 : 50;
              const y = 100 - ((item.score / item.total) * 100);
              return <circle key={`${item.label}-${index}`} cx={x} cy={y} r="2.8" className={item.passed ? 'score-dot pass' : 'score-dot fail'} />;
            })}
          </svg>
          <div className="chart-label-row">
            {items.map((item, index) => (
              <span key={`${item.label}-${index}`}>{item.score}/{item.total}</span>
            ))}
          </div>
        </>
      ) : (
        <div className="chart-empty">No score history yet</div>
      )}
    </div>
  );
}

function CategoryChart({ items }) {
  return (
    <div className="chart-card">
      <div className="chart-head">
        <div>
          <h3>Category Accuracy</h3>
          <span>Lower bars need more revision</span>
        </div>
      </div>

      <div className="category-chart">
        {items.length ? items.map((item) => (
          <div className="category-row" key={item.category}>
            <div className="category-row-label">
              <strong>{item.category}</strong>
              <span>{item.correct} correct, {item.wrong} wrong</span>
            </div>
            <div className="category-track" aria-label={`${item.category} accuracy ${item.accuracy}%`}>
              <span style={{ width: `${item.accuracy}%` }} />
            </div>
            <em>{item.accuracy}%</em>
          </div>
        )) : (
          <div className="chart-empty">Complete a test to see category accuracy</div>
        )}
      </div>
    </div>
  );
}

function CorrectSplit({ analytics }) {
  const latestCorrect = analytics.latestScore;
  const latestWrong = Math.max(analytics.latestTotal - analytics.latestScore, 0);
  const correctPct = analytics.latestTotal ? Math.round((latestCorrect / analytics.latestTotal) * 100) : 0;

  return (
    <div className="chart-card split-card">
      <div className="chart-head">
        <div>
          <h3>Latest Attempt Split</h3>
          <span>Correct vs incorrect</span>
        </div>
      </div>
      <div className="donut-wrap">
        <div className="donut" style={{ '--score': `${correctPct}%` }}>
          <strong>{correctPct}%</strong>
          <span>correct</span>
        </div>
        <div className="split-legend">
          <span><i className="legend-dot success" /> {latestCorrect} correct</span>
          <span><i className="legend-dot danger" /> {latestWrong} incorrect</span>
        </div>
      </div>
    </div>
  );
}

function AIRecommendationCard({ recommendation, isLoading, source, error }) {
  return (
    <section className="panel-card ai-dashboard-card">
      <div className="section-heading">
        <div>
          <h2>AI Learning Coach</h2>
          <span>{source === 'gemini' ? 'Generated by Gemini through the VanLoka backend' : 'Personalized local guidance'}</span>
        </div>
        <span className={`status-pill ${source === 'gemini' ? 'success' : 'warning'}`}>{source === 'gemini' ? 'AI live' : 'Fallback'}</span>
      </div>

      {isLoading ? (
        <div className="ai-dashboard-loading">
          <span />
          <span />
          <span />
        </div>
      ) : (
        <div className="ai-dashboard-content">
          <p>{recommendation.summary}</p>

          <div className="recommendation-grid">
            <div>
              <h3>Focus Areas</h3>
              <div className="focus-chip-list">
                {(recommendation.focusAreas?.length ? recommendation.focusAreas : ['Mixed revision']).map((item) => (
                  <span className="focus-chip" key={item}>{item}</span>
                ))}
              </div>
            </div>
            <div>
              <h3>Readiness</h3>
              <strong className="readiness-label">{recommendation.readiness}</strong>
            </div>
          </div>

          <div className="study-plan">
            <h3>Personal Study Plan</h3>
            {recommendation.studyPlan?.map((item, index) => (
              <div className="study-step" key={`${item}-${index}`}>
                <strong>{index + 1}</strong>
                <span>{item}</span>
              </div>
            ))}
          </div>

          <div className="next-action-card">
            <span>Best next action</span>
            <strong>{recommendation.nextAction}</strong>
          </div>

          {error && <p className="ai-error-note">{error}</p>}
        </div>
      )}
    </section>
  );
}

function Dashboard() {
  const navigate = useNavigate();
  const { user } = useAuth();
  const [history, setHistory] = useState(() => readTestHistory());
  const analytics = useMemo(() => buildDashboardAnalytics(history), [history]);
  const trainee = useMemo(() => getVerifiedTrainee() || user, [user]);
  const [aiState, setAiState] = useState({
    recommendation: getLocalRecommendation(analytics),
    source: 'local',
    error: '',
    loading: false,
  });

  useEffect(() => {
    let isMounted = true;
    setAiState((current) => ({
      ...current,
      recommendation: getLocalRecommendation(analytics),
      source: 'local',
      error: '',
      loading: true,
    }));

    fetchDashboardRecommendation({ analytics, trainee })
      .then((nextState) => {
        if (!isMounted) return;
        setAiState({
          recommendation: nextState.recommendation,
          source: nextState.source,
          error: nextState.error,
          loading: false,
        });
      });

    return () => {
      isMounted = false;
    };
  }, [analytics, trainee]);

  const clearHistory = () => {
    localStorage.removeItem('vanloka_test_history');
    setHistory([]);
  };

  return (
    <main className="app-shell dashboard-shell advanced-dashboard-shell">
      <PageTopNav />

      <section className="dashboard-workspace">
        <header className="panel-card dashboard-header advanced-dashboard-header">
          <div className="dashboard-header-copy">
            <span className="eyebrow">AI enabled learning dashboard</span>
            <h1>{trainee?.name ? `${trainee.name}'s progress` : 'Progress dashboard'}</h1>
            <p>Track test readiness, weak categories, attempt trends, and the next learning move from one place.</p>
          </div>
          <div className="dashboard-header-actions">
            <button className="btn primary" onClick={() => navigate('/test', { state: { trainee } })} type="button">
              Start Mock Test
            </button>
            <button className="btn outline" disabled={!history.length} onClick={clearHistory} type="button">
              Clear History
            </button>
          </div>
        </header>

        <section className="analytics-metric-grid" aria-label="Dashboard metrics">
          <MetricCard label="Readiness" value={getReadinessLabel(analytics)} detail={`${analytics.passRate}% pass rate`} tone={analytics.bestScore >= analytics.passMark ? 'success' : 'warning'} />
          <MetricCard label="Attempts" value={analytics.totalAttempts} detail={`${analytics.passedAttempts} passed`} />
          <MetricCard label="Best Score" value={`${analytics.bestScore}/20`} detail={`Target ${analytics.passMark}/20`} tone={analytics.bestScore >= analytics.passMark ? 'success' : 'warning'} />
          <MetricCard label="Average Score" value={`${analytics.averageScore}/20`} detail="Across all attempts" />
          <MetricCard label="Latest Score" value={`${analytics.latestScore}/20`} detail={analytics.totalAttempts ? 'Most recent attempt' : 'No attempt yet'} />
          <MetricCard label="Average Time" value={formatTime(analytics.averageTime)} detail="Time management" />
        </section>

        <section className="dashboard-analytics-grid">
          <div className="span-7">
            <ScoreTrendChart items={analytics.scoreTrend} passMark={analytics.passMark} />
          </div>
          <div className="span-5">
            <CorrectSplit analytics={analytics} />
          </div>
          <div className="span-7">
            <CategoryChart items={analytics.categoryPerformance} />
          </div>
          <aside className="panel-card weak-area-card span-5">
            <div className="section-heading">
              <div>
                <h2>Weak Areas</h2>
                <span>Prioritized by wrong answers</span>
              </div>
            </div>
            <div className="weak-area-list">
              {analytics.weakCategories.length ? analytics.weakCategories.map((item, index) => (
                <div className="weak-area-item" key={item.category}>
                  <strong>{index + 1}</strong>
                  <div>
                    <span>{item.category}</span>
                    <em>{item.wrong} wrong answers, {item.accuracy}% accuracy</em>
                  </div>
                </div>
              )) : (
                <div className="chart-empty">No weak areas yet. Complete a test to generate analytics.</div>
              )}
            </div>
          </aside>
        </section>

        <AIRecommendationCard
          error={aiState.error}
          isLoading={aiState.loading}
          recommendation={aiState.recommendation}
          source={aiState.source}
        />

        <section className="panel-card recent-attempts-card">
          <div className="section-heading">
            <div>
              <h2>Recent Attempts</h2>
              <span>Last five completed mock tests</span>
            </div>
            <Link className="btn outline" to="/results">Review Latest Result</Link>
          </div>

          <div className="attempt-table">
            <div className="attempt-row attempt-head">
              <span>Date</span>
              <span>Score</span>
              <span>Time</span>
              <span>Status</span>
            </div>
            {analytics.recentAttempts.length ? analytics.recentAttempts.map((attempt) => (
              <div className="attempt-row" key={attempt.id}>
                <span>{attempt.date}</span>
                <strong>{attempt.score}/{attempt.total}</strong>
                <span>{formatTime(attempt.timeTaken)}</span>
                <em className={attempt.passed ? 'pass-text' : 'fail-text'}>{attempt.passed ? 'Passed' : 'Needs review'}</em>
              </div>
            )) : (
              <div className="empty-state compact">
                <p>No attempts yet. Start a mock test to unlock analytics and AI recommendations.</p>
                <button className="btn primary" onClick={() => navigate('/test', { state: { trainee } })} type="button">Start First Test</button>
              </div>
            )}
          </div>
        </section>
      </section>
    </main>
  );
}

export default Dashboard;
